version: "3.8"

services:
  mobilya:
    image: ghcr.io/topalogluonur53/mobilya:latest
    container_name: mobilya_app
    restart: unless-stopped

    ports:
      - "8090:8000"

    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1

    volumes:
      - /DATA/AppData/mobilya/db.sqlite3:/app/db.sqlite3
      - /DATA/AppData/mobilya/static:/app/static

x-casaos:
  architectures:
    - amd64
    - arm64
    - arm

  main: mobilya

  title:
    custom: Mobilya Planlayıcı

  description:
    en: Cabinet planning and cutlist tool
    tr: Dolap planlama ve kesim listesi uygulaması

  icon: https://cdn-icons-png.flaticon.com/512/3052/3052210.png

  category: Utilities
  author: Onur Topaloğlu
