version: '3.8'

services:
  app:
    image: ghcr.io/topalogluonur53/mobilya:latest
    container_name: CAD_Planlayici
    restart: always
    ports:
      - "4000:4000"
      - "4040:4040"
    volumes:
      # Veritabanının CasaOS kapanıp açıldığında silinmesini engeller
      - ./db.sqlite3:/app/db.sqlite3
      # Statik dosyaların klasörünü harici tutar
      - ./static:/app/static

x-casaos:
  architectures:
    - amd64
    - arm64
    - arm
  main: app
  port_map: "4000"
  title:
    custom: CAD Planlayıcı
  description:
    en: Mutfak Dolabı 3D CAD Planlama ve Kesim Listesi Uygulaması
    tr: Mutfak Dolabı 3D CAD Planlama ve Kesim Listesi Uygulaması
  icon: "https://cdn-icons-png.flaticon.com/512/3052/3052210.png"
  category: "Utilities"
  author: "onur topaloglu"
