version: "3.8"

services:
  app:
    image: ghcr.io/topalogluonur53/mobilya:latest
    container_name: CAD_Planlayici
    restart: unless-stopped
    ports:
      - "4000:4000"
      - "4040:4040"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    volumes:
      - /DATA/AppData/mobilya/db.sqlite3:/app/db.sqlite3
      - /DATA/AppData/mobilya/static:/app/static

x-casaos:
  architectures:
    - amd64
    - arm64
    - arm
  main: app
  port_map: "4000"
  title:
    custom: Mobilya Planlayıcı

  description:
    en: Cabinet planning and cutlist tool
    tr: Dolap planlama ve kesim listesi uygulaması

  icon: https://cdn-icons-png.flaticon.com/512/3052/3052210.png

  category: Utilities
  author: Onur Topaloğlu
