# Generated by Django 6.0.3 on 2026-03-03 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('layout_type', models.CharField(choices=[('STRAIGHT', 'Straight'), ('L', 'L-Shape')], default='STRAIGHT', max_length=20)),
                ('panel_thickness', models.IntegerField(default=18)),
                ('base_depth', models.IntegerField(default=560)),
                ('base_height', models.IntegerField(default=720)),
                ('wall_depth', models.IntegerField(default=320)),
                ('wall_height', models.IntegerField(default=720)),
                ('module_set', models.CharField(default='300,400,450,500,600,800,900', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1)),
                ('length_mm', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='planner.project')),
            ],
        ),
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('BASE', 'Base '), ('WALL', 'Wall'), ('TALL', 'Tall'), ('FILLER', 'Filler'), ('APPL', 'Appliance')], max_length=20)),
                ('start_mm', models.IntegerField()),
                ('width_mm', models.IntegerField()),
                ('depth_mm', models.IntegerField()),
                ('height_mm', models.IntegerField()),
                ('label', models.CharField(blank=True, max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabinets', to='planner.project')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabinets', to='planner.segment')),
            ],
        ),
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('FRIDGE', 'Fridge'), ('DW', 'Dishwasher'), ('OVEN', 'Oven'), ('SINK', 'Sink'), ('HOOD', 'Hood'), ('CORNER', 'Corner Block')], max_length=20)),
                ('start_mm', models.IntegerField()),
                ('width_mm', models.IntegerField()),
                ('note', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appliances', to='planner.project')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appliances', to='planner.segment')),
            ],
        ),
    ]
