# Generated by Django 6.0.3 on 2026-03-03 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinet',
            name='has_drawers',
            field=models.BooleanField(default=False),
        ),
    ]
