# Generated by Django 5.2.9 on 2026-03-03 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_cabinet_has_drawers'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='height_mm',
            field=models.IntegerField(default=2500),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cabinet',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='base_depth',
            field=models.IntegerField(default=600),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='segment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
