# Generated by Django 5.2.9 on 2026-03-03 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_segment_height_mm_alter_appliance_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinet',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
