# Generated by Django 6.0.3 on 2026-03-04 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_cabinet_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='gap_height',
            field=models.IntegerField(default=600),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cabinet',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='segment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
