# Generated by Django 5.2.9 on 2026-03-04 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_project_gap_height_alter_appliance_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliance',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cabinet',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='segment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
