# Generated by Django 5.2.9 on 2026-03-04 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_alter_appliance_id_alter_cabinet_id_alter_project_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinet',
            name='code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='type',
            field=models.CharField(choices=[('FRIDGE', 'Buzdolabı'), ('DW', 'Bulaşık Makinesi'), ('OVEN', 'Fırın'), ('SINK', 'Eviye'), ('HOOD', 'Davlumbaz'), ('CORNER', 'Köşe Modülü')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cabinet',
            name='kind',
            field=models.CharField(choices=[('BASE', 'Alt Dolap'), ('WALL', 'Üst Dolap'), ('TALL', 'Boy Dolap'), ('FILLER', 'Kör Parça'), ('APPL', 'Beyaz Eşya')], max_length=20),
        ),
    ]
