# Generated by Django 5.2.9 on 2026-03-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_cabinet_code_alter_appliance_type_alter_cabinet_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinet',
            name='door_style',
            field=models.CharField(choices=[('AUTO', 'Otomatik'), ('1', '1 Kapaklı'), ('2', '2 Kapaklı'), ('4', '4 Kapaklı')], default='AUTO', max_length=10),
        ),
    ]
