# Generated by Django 5.2.9 on 2026-03-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0008_cabinet_door_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinet',
            name='partition_style',
            field=models.CharField(choices=[('AUTO', 'Otomatik'), ('1', 'Bölmesiz'), ('2', '2 Bölmeli'), ('4', '4 Bölmeli')], default='AUTO', max_length=10),
        ),
    ]
