# Generated by Django 5.2.9 on 2026-03-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0009_cabinet_partition_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliance',
            name='height_mm',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
