# Generated by Django 5.2.9 on 2026-03-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0010_appliance_height_mm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet',
            name='kind',
            field=models.CharField(choices=[('BASE', 'Alt Dolap'), ('WALL', 'Üst Dolap'), ('TALL', 'Boy Dolap'), ('FILLER', 'Kör Parça'), ('APPL', 'Beyaz Eşya'), ('EMPTY_BASE', 'Boşluk (Alt)'), ('EMPTY_WALL', 'Boşluk (Üst)')], max_length=20),
        ),
    ]
