# Generated by Django 5.2.9 on 2026-03-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0011_alter_cabinet_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='countertop_height',
            field=models.IntegerField(default=40),
        ),
        migrations.AddField(
            model_name='project',
            name='toe_kick_height',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='base_height',
            field=models.IntegerField(default=760),
        ),
        migrations.AlterField(
            model_name='project',
            name='wall_height',
            field=models.IntegerField(default=760),
        ),
    ]
